- name: Prepare
  hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: add apt signing key for mariadb
      ansible.builtin.apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: present

    - name: Add mariadb repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://mariadb.mirror.globo.tech/repo/10.5/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.selinux
    - role: robertdebock.container_docs
    - role: robertdebock.mysql
      mysql_databases:
        - name: zabbix
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: zabbix
          password: zabbix
          priv: "zabbix.*:ALL"
    - role: robertdebock.ca_certificates
    - role: robertdebock.zabbix_repository
    - role: robertdebock.core_dependencies

- name: Install Zabbix
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: robertdebock.zabbix_server
    - role: robertdebock.zabbix_web