---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.ca_certificates
  - name: robertdebock.core_dependencies
  - name: robertdebock.container_docs
  - name: robertdebock.mysql
    src: git+https://github.com/robertdebock/ansible-role-mysql
  - name: robertdebock.selinux
  - name: robertdebock.zabbix_repository
  - name: robertdebock.zabbix_server
    src: git+https://github.com/robertdebock/ansible-role-zabbix_server
  - name: android06.zabbix_web
    src: git+https://github.com/Android60-projects/ansible-role-zabbix_web
  - name: robertdebock.zabbix_agent
collections:
  - name: ansible.posix
  - name: community.mysql